export { default as CustomerLayout } from './CustomerLayout'
export { default as StaffLayout } from './StaffLayout'
export { default as ManagerLayout } from './ManagerLayout'
export { default as AdminLayout } from './AdminLayout'
export { default as AuthLayout } from './AuthLayout'
